name: AdvancedFlowers
version: ${project.version}
main: com.blovien.advancedflowers.AdvancedFlowers
api-version: 1.16
authors: [ Blovien ]
description: Create custom flowers

commands:
  createflower:
    aliases: [createadvancedflower, cf]
    description: Open the AdvancedFlower gui
